theme: jekyll-theme-minimal

title: Asynchronous Many-Task systems for Exascale 2023
logo: /assets/logo.png
conf_city: Glasgow, Scotland, United Kingdom
acronym: AMTE 2023
workshop_date: Tuesday, 23  August 2023
